ask/ask/urls.py
from django.contrib import admin
from django.urls import path, include
from app import views
from django.contrib.auth import views as auth_views
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from app.models import LikeDislike
from app.models import Article, Comment
from app.views import CreateAccount, SettingProfile, CreatePost, Questions
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),

    path('', views.index, name='index'),
    path('hot/', views.index, name='hot'),

    path('question/<int:qid>/', Questions.as_view(), name='question_page'),
    path('signup/', CreateAccount.as_view(), name='signup'),
    path('ask/', CreatePost.as_view(), name='new_question'),
    path('profile', SettingProfile.as_view(), name='user_profile'),

    path('login/', auth_views.LoginView.as_view(), name="login"),
    path('logout/', auth_views.LogoutView.as_view(), name="logout"),
    path('password-change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('password-change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),

    path('tag/<slug:tag_slug>', views.index, name='tag_page'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ask/app/forms.py
from django import forms
from taggit.forms import TagField
from django.utils import timezone


from .models import Question, Answer, Profile


class AddPost(forms.ModelForm):
    class Meta:
        model = Question
        exclude = ['author_id']

        title = forms.CharField(label='Question title', widget=forms.TextInput(attrs={'class': 'form-control', 'size': 64}))
        text = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control', 'size': 64}), label='Question text')
        tags = TagField( label='Tags', widget=forms.TextInput(attrs={'class': 'form-control'}))
        create_date = timezone.now()
        required_css_class = "fields"


class AddAnswer(forms.ModelForm):
    class Meta:
        model = Answer
        exclude = ['question', 'author_id', 'create_date']

        text = forms.CharField(widget=forms.Textarea(attrs={'class': 'textarea control-check', 'size': 64}), label='Answer text')


class AddRegister(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['username', 'first_name', 'last_name', 'email', 'password', 'img']

        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control', 'size': 64}),
            'first_name': forms.TextInput(attrs={'class': 'form-control', 'size': 64}),
            'last_name': forms.TextInput(attrs={'class': 'form-control', 'size': 64}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'size': 64}),
            'password': forms.PasswordInput(attrs={'class': 'form-control', 'size': 64}),
            'img': forms.FileInput(attrs={'upload_to': 'media'}).attrs.update({'required': False})
        }


class SettingUser(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['email', 'first_name', 'last_name', 'img']
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control', 'size': 64}),
            'last_name': forms.TextInput(attrs={'class': 'form-control', 'size': 64}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'required': False}),
            'img': forms.FileInput(attrs={'upload_to': 'media'}).attrs.update({'required': False})
        }

ask/templates/answers.html
{% load static %}


 {% if user.is_authenticated %}
    <div class="my-3 p-3 bg-white rounded shadow-sm">
        <div class="form-section">
                <form action="{% url 'question_page' question.id %}" method="POST">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md-8">
                            {{ form.non_field_errors }}
                            <div class="fieldWrapper">
                                 {{ form.text.errors }}
                                    <textarea name="text" cols="90" rows="5" required="" wrap="hard" id="id_text"></textarea>
                            </div>
                        <button type="submit" class="btn btn-outline-info">Post it</button>
                        </div>
                    </div>

                    </form>
            </div>
    </div>
 {% endif %}

    <div class="my-3 p-3 bg-white rounded shadow-sm">
    <h6 class="border-bottom border-gray pb-2 mb-0">All comments</h6>

        {% for comment in comments %}
        <div class="media text-muted pt-3">
      <img alt="{{ users.username }}" height="70px" class="answ-img" src="{{comment.author_id.img.url}}">


            <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
        <strong class="d-block text-gray-dark">{{ comment.author_id}}</strong>
        {{ comment.text }}
             {% if user.is_authenticated %}
                <div class="pad-ver">
                <button type="button" class="btn btn-outline-success">↑</button>
                <button type="button" class="btn btn-outline-warning">↓</button>
        </div>
         {% endif %}

    </div>
        {% endfor %}
        <div class="pagination">
    <span class="step-links">
        {% if comments.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ comments.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ comments.number }} of {{ comments.paginator.num_pages }}.
        </span>

        {% if comments.has_next %}
            <a href="?page={{ comments.next_page_number }}">next</a>
            <a href="?page={{ comments.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
    </div>

ask/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
      <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">

    <title>Asc</title>
  </head>
<body>

{% include 'inc/Navbar.html' %}
  <div class="container-fluid m-5">
    <div class="row">

        <div class="col-8">

        {% block content %} {% endblock content %}
        </div><!-- вопросы -->

            {% include 'inc/right_menu.html' %}

  </div><!-- /.row -->

</div>

    <!-- Optional JavaScript -->
   </body>
</html>

ask/templates/create_post.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <div class="col-md">
        <h2> Ask some Question</h2>

        <div class="my-3 p-3 bg-white rounded shadow-sm">

            <div class="form-section">
                <form action="{% url 'new_question' %}" method="POST">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-10 label-inputs">
                            {{ form.as_p }}
                        <button type="submit" class="btn btn-outline-info">Post it</button>
                        </div>
                    </div>

                    </form>
            </div>
        </div>
    </div>
{% endblock %}

ask/templates/hot.html
{% extends 'base.html' %}

{% block content %}
    {% for question in questions %}
        {% include 'inc/question.html'%}
    {% endfor %}

    {% include 'inc/page_navig.html' %}
{% endblock content %}

ask/templates/index.html
{% extends 'base.html' %}

{% block content %}

    {% for question in questions %}
        {% include 'inc/question.html'%}
    {% endfor %}

    {% include 'inc/page_navig.html' %}
{% endblock content %}

ask/templates/question.html
{% extends 'base.html' %}

{% block content %}
    {% include 'inc/question.html'%}
    {% include 'answers.html' %}
{% endblock content %}

ask/templates/signup.html
{% extends 'base.html' %}

{% block content %}



<main class="main ml-5" >
       <div class="my-3 p-3 bg-white rounded shadow-sm">
        <div class="form-section">
            <form action="{% url 'signup' %}" enctype="multipart/form-data" method="POST">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md-8">
                            {% for field in form %}
                                <div class="form-droup">
                                {% if field.errors %}
                                    <div class="alert alert-danger">
                                        {{ field.errors }}
                                    </div>
                                {% endif %}
                                {{ field.label }}
                                {{ field }}
                                <br>
                                </div>
                            {% endfor %}
                            <br>
                        <button type="submit" class="btn btn-outline-info">Restration</button>
                        </div>
                    </div>
            </form>
            </div>
    </div>

  </main>
{% endblock content %}

ask/templates/user_profile.html
{% extends 'base.html' %}

{% block content %}


<main class="main ml-5" >
       <div class="my-3 p-3 bg-white rounded shadow-sm">
        <div class="form-section">
            <form action="{% url 'user_profile' %}" enctype="multipart/form-data" method="POST">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md-8">
                            {% for field in form %}
                                <div class="form-droup">
                                {{ field.label }}
                                {{ field }}
                                <br>
                                </div>
                            {% endfor %}
                        <br>
                         <div class="mb-3">
                            <a class="btn btn-primary" href="{% url 'password_change'%}">Change password</a>
                         </div>
                        <button type="submit" class="btn btn-outline-info">Restration</button>
                        </div>
                    </div>
            </form>
            </div>
    </div>

  </main>
</main>

{% endblock content %}